### ISSUE TITLE
Implement game rules

### ISSUE THREAD

**Issue by PauMAVA** [feather-rs/libcraft#3]
As discussed in [#251](https://github.com/feather-rs/feather/issues/251) on the `feather` repo we should implement the game rules in `libcraft` without using a macro-based approach. 

I will try to implement this and open a PR when done and tested.

**Comment by PauMAVA** [comment]
Instead of creating a struct with all the game rules, as done in the current implementation, or creating an enum (for which it would be difficult to implement the `Default` trait) what do you think about a struct containing the game rule name and value?
```rust
pub struct GameRule<T> {
    kind: GameRuleKind,
    value: T,
}
```
It would be a similar approach to the `Enchantment` implementation. Then saving a `BTreeSet` with one struct per game rule.

**Comment by Defman** [comment]
There is not many game rules, so this approach is going to increase the complexity, storage, and would require an indirect lookup. Since the signature of the `BTreeSet` would be `BTreeSet<Box<GameRule>>`. I think we should stick to having a monolithic struct with all the gam rules. That said, what do you think the benefits of your approach would be?

**Comment by PauMAVA** [comment]
It would be good in the far future for easy scalability when lots of game rules could be added. But for now, the monolithic struct will do. 

Since which version should I add game rules? 1.16?

**Comment by Defman** [comment]
1.16, yes that is correct.
