### ISSUE TITLE
Move BlockKind enum from feather to libcraft

### ISSUE THREAD

**Issue by kallekankaanpaa** [feather-rs/libcraft#7]
We need the BlockKind enum to continue with #2. Since the enum is generated we need to also move the generator for it. 

Should we move all other generators at the same time and should we stick with the python generators or rewrite those in rust?

**Comment by caelunshun** [comment]
> Should we move all other generators at the same time and should we stick with the python generators or rewrite those in rust?

I've found Python to be more ergonomic for writing this sort of generator, though I'm fine with either keeping the existing generators or switching to Rust.

Moving all the generators is not a bad idea, but we need to reorganize the code. Right now, all the generated structs are globbed together in the `feather-generated` crate. For `libcraft`, we should have a separate crate for each piece of generated info—so `BlockKind` goes into `libcraft-blocks`, and `Item` goes into `libcraft-items`. 

Some generated enums (`EntityKind` and `Particle`) probably belong in `libcraft-core`, since they're too small to have their own crates.

**Comment by kallekankaanpaa** [comment]
Easiest way forward is keeping the existing generators.

Should we create new `libcraft-generators` crate that would contain all the generators and common code shared by them. and just save the generated info on all of the different crates? Then we should also move the current block state generator from `libcraft-blocks-generator` to the new `libcraft-generators` crate.

**Comment by PauMAVA** [comment]
This would be a good idea in order to keep the different generators separated. I will need this to continue with #6.
